### ISSUE TITLE
Potentially closed bars

### ISSUE THREAD

**Issue by ironjan** [codeforpb/Kneipenplan#17]
* Chamäleon is only listed in the kneipenplan, no homepage except for the outdated facebook page is found https://www.facebook.com/pages/Chamäleon-Paderborn
* Casa Nova. Same as Chamäleon, without fb-page
* Sketch. http://www.sketch-cocktailbar.de/ is down, fb-page (https://www.facebook.com/sketchpb) no updates since june

**Comment by HerHde** [comment]
I wrote an email to the [Pflaumenbaum](http://www.pflaumenbaum-paderborn.de/). Someone mentioned that they closed.
