### ISSUE TITLE
Use better icons

### ISSUE THREAD

**Issue by ironjan** [codeforpb/Kneipenplan#2]
We should ask the fachschaft for the "burger" and "beer" icons they are using.

**Comment by HerHde** [comment]
How about these Icons/SVG (Public Domain):
https://commons.wikimedia.org/wiki/File:Aiga_restaurant_2.svg
https://commons.wikimedia.org/wiki/File:Aiga_bar.svg

**Comment by HerHde** [comment]
I altered the restaurant-icon to be red and crossed for better overview while being friendly for most color blindnesses with fce58958bbee968bf5631ad62e2121f69d42f90a.
Any proposals or can I close this?

**Comment by ironjan** [comment]
It probably would be better not to use red for these images (it's a warning color) ;)

**Comment by HerHde** [comment]
The contrast is too low with only black icons. Red is also the color of hunger.
But how about grey for the food icons? Or this icon: http://commons.wikimedia.org/wiki/File:Aiga_restaurant_inv.svg
@arndot said it would be too inconsistent to use a framed one and one without.

**Comment by ironjan** [comment]
Since the main focus of the Kneipenplan is on bars etc., grey would be a good choice - food is just a secondary information in this case (most people get hungry after going to some bars and drinking some beers).

**Comment by HerHde** [comment]
Okay, with 39742ef055227814ead03aded94e10047ab0c517 I've chosen a grey with enough contrast to black and the grey of the map. I think even dogs could see the difference.
What do you think?

**Comment by ironjan** [comment]
Looks good to me.
